### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by LIGHTNING-top** [LIGHTNING-top/magot#3]
How to use useSelector in React.
And also, i want to know useRef, too

**Comment by MetaFomos** [comment]
With mapState, all individual fields were returned in a combined object. It didn't matter if the return object was a new reference or not - connect() just compared the individual fields. With useSelector(), returning a new object every time will always force a re-render by default. If you want to retrieve multiple values from the store, you can:

Call useSelector() multiple times, with each call returning a single field value
Use Reselect or a similar library to create a memoized selector that returns multiple values in one object, but only returns a new object when one of the values has changed.
Use the shallowEqual function from React-Redux as the equalityFn argument to useSelector(), like:

import { shallowEqual, useSelector } from 'react-redux'

// later
const selectedData = useSelector(selectorReturningObject, shallowEqual)

Thanks in advance!!!

**Comment by k-star-229** [comment]
Thanks Metafomos

**Comment by k-star-229** [comment]
> With mapState, all individual fields were returned in a combined object. It didn't matter if the return object was a new reference or not - connect() just compared the individual fields. With useSelector(), returning a new object every time will always force a re-render by default. If you want to retrieve multiple values from the store, you can:
> 
> Call useSelector() multiple times, with each call returning a single field value Use Reselect or a similar library to create a memoized selector that returns multiple values in one object, but only returns a new object when one of the values has changed. Use the shallowEqual function from React-Redux as the equalityFn argument to useSelector(), like:
> 
> import { shallowEqual, useSelector } from 'react-redux'
> 
> // later const selectedData = useSelector(selectorReturningObject, shallowEqual)
> 
> Thanks in advance!!!
